export interface RegisterPayload {
  name: string
  email: string
  password: string
  password_confirmation: string
  /**
   * Username de login. Deprecated como input do formulario, agora vai
   * sempre = email. Mantido na interface enquanto o backend ainda exige
   * o campo (vamos remover a obrigatoriedade na proxima migration).
   */
  login?: string
  /** Telefone agora e opcional no cadastro — coletado em /settings depois. */
  celular?: string
  /** Codigo do assessor — removido do formulario default mas a interface
   *  continua aceitando pra fluxos B2B antigos. */
  advisor_code?: string
}

export interface LoginPayload {
  login: string
  password: string
}

export interface LoginResponse {
  access_token: string
  token_type: string
  expires_in: number
}

export interface AuthResponse {
  token: string
  user?: {
    id: string | number
    name: string
    email: string
    login?: string
    celular?: string
  }
}

export const useAuthService = () => {
  const { authFetch } = useCustomFetch()
  const config = useRuntimeConfig()
  const baseURL = `${config.public.apiBaseUrl}/auth`

  async function register(body: RegisterPayload): Promise<AuthResponse> {
    const resp = await $fetch<AuthResponse>(`${baseURL}/register`, {
      method: 'POST',
      credentials: 'include',
      body,
    })
    return resp
  }

  async function login(body: LoginPayload): Promise<LoginResponse> {
    const resp = await $fetch<LoginResponse>(`${baseURL}/login`, {
      method: 'POST',
      credentials: 'include',
      body,
    })
    return resp
  }

  async function me() {
    const resp = await authFetch(`${baseURL}/me`, {
      method: 'GET',
    })
    return resp
  }

  async function logout() {
    const resp = await authFetch(`${baseURL}/logout`, {
      method: 'POST',
    })
    return resp
  }

  async function updateProfile(body: {
    name?: string
    celular?: string
    /** E.164 ja normalizado (ex: +5511999999999). Quando vazio, mantem
     *  o valor antigo no backend (PUT parcial). */
  }) {
    const resp = await authFetch(`${baseURL}/profile`, {
      method: 'PUT',
      body,
    })
    return resp
  }

  async function changePassword(body: {
    current_password: string
    password: string
    password_confirmation: string
  }) {
    const resp = await authFetch(`${baseURL}/password`, {
      method: 'PUT',
      body,
    })
    return resp
  }

  async function becomeAdvisor() {
    const resp = await authFetch(`${baseURL}/become-advisor`, {
      method: 'POST',
    })
    return resp
  }

  /**
   * Step 1 of password reset — backend ALWAYS returns 200 with the
   * same generic message regardless of whether the email is registered
   * (anti-enumeration). The error path here only fires on
   * network/throttle failures, never on "unknown email".
   */
  async function forgotPassword(body: { email: string }): Promise<{ message: string }> {
    return await $fetch<{ message: string }>(`${baseURL}/forgot-password`, {
      method: 'POST',
      body,
    })
  }

  /**
   * Step 2 of password reset — token + email arrive via the URL
   * query string (the email link generated by the backend). Backend
   * returns 200 on success or 422 with a Portuguese error message
   * when the token is invalid/expired.
   */
  async function resetPassword(body: {
    token: string
    email: string
    password: string
    password_confirmation: string
  }): Promise<{ message: string }> {
    return await $fetch<{ message: string }>(`${baseURL}/reset-password`, {
      method: 'POST',
      body,
    })
  }

  return {
    register,
    login,
    me,
    logout,
    updateProfile,
    changePassword,
    becomeAdvisor,
    forgotPassword,
    resetPassword,
  }
}
