/**
 * useCitationProse — mount hover-preview cards on `[N]` citation refs.
 *
 * Same pattern as `useTickerProse` / `useGlossaryProse`:
 *
 *   1. Marked extension is NOT involved here — citations are
 *      generated by `decorateHtml()` in Message.vue via a regex
 *      replacement (`[N]` → `<sup class="chat-citation-mount"
 *      data-cite-id="N">N</sup>`). The post-mount step finds those
 *      placeholders and swaps them with `<CitationChip>` Vue
 *      instances that render a hover preview card with title, URL,
 *      publisher, date.
 *
 *   2. Citations are looked up in the message's own `citations[]`
 *      array (`ChatCitation { id, source }`). The composable
 *      receives a `getCitations()` accessor so the caller can pass
 *      a reactive source — when streaming adds new citations, the
 *      next `mountIn()` call wires them.
 *
 *   3. Cleanup unmounts every chip we touched, just like the other
 *      prose composables.
 *
 * Why post-mount + Teleport
 * -------------------------
 * Tooltips need to escape `overflow:hidden` ancestors (chat tables,
 * scroll containers). The CitationChip uses `<Teleport to="body">`
 * to render the preview outside the chat thread, with `position:
 * fixed` coordinates re-computed on hover/scroll/resize.
 */
import {
  type ComponentInternalInstance,
  createVNode,
  render,
  getCurrentInstance,
} from 'vue'
import CitationChip from '~/components/atoms/CitationChip.vue'
import type { ChatCitation } from '~/composables/useChatStream'

export function useCitationProse() {
  const instance = getCurrentInstance() as ComponentInternalInstance | null
  const mountedSpans = new Set<HTMLElement>()

  /**
   * Walk every `.chat-citation-mount[data-cite-id]` placeholder in
   * `root` and swap it for a `<CitationChip>` instance. Skips
   * placeholders already mounted (`data-mounted="1"`) so streaming
   * re-renders don't double-mount.
   *
   * @param root        Element wrapping the rendered markdown.
   * @param citations   Array of citations on the current message —
   *                    used to look up source metadata by id.
   */
  function mountIn(
    root: HTMLElement | null | undefined,
    citations: ChatCitation[] | undefined,
  ): void {
    if (!root || !instance) return
    if (typeof window === 'undefined') return // SSR no-op
    const placeholders = root.querySelectorAll<HTMLElement>(
      '.chat-citation-mount[data-cite-id]',
    )
    if (!placeholders.length) return
    // Build a quick lookup of id → source so we don't .find() per
    // placeholder for big citation lists.
    const sourceById = new Map<number, ChatCitation['source']>()
    for (const c of citations ?? []) {
      sourceById.set(c.id, c.source)
    }
    placeholders.forEach((sup) => {
      if (sup.dataset.mounted === '1') return
      const idRaw = sup.dataset.citeId
      if (!idRaw) return
      const id = Number.parseInt(idRaw, 10)
      if (!Number.isFinite(id)) return
      const source = sourceById.get(id) ?? null
      try {
        const vnode = createVNode(CitationChip, { id, source })
        vnode.appContext = instance.appContext
        sup.textContent = ''
        render(vnode, sup)
        sup.dataset.mounted = '1'
        mountedSpans.add(sup)
      } catch (err) {
        // Defensive: if the mount throws (router context missing,
        // tooltip lib unavailable, etc.), restore the original
        // numeric content so the chat doesn't display an empty
        // sup tag. Plain text loses the hover preview but
        // remains readable.
        if (typeof console !== 'undefined') {
          // eslint-disable-next-line no-console
          console.warn('[citation] mount failed for', id, err)
        }
        sup.textContent = String(id)
        sup.classList.remove('chat-citation-mount')
      }
    })
  }

  function cleanup(): void {
    if (typeof window === 'undefined') return
    mountedSpans.forEach((sup) => {
      render(null, sup)
      sup.removeAttribute('data-mounted')
    })
    mountedSpans.clear()
  }

  return { mountIn, cleanup }
}
